### ISSUE TITLE
SDK use wrong endpoint

### ISSUE THREAD

**Issue by shrujalshah28** [Flagsmith/flagsmith-nodejs-client#41]
https://github.com/Flagsmith/flagsmith-nodejs-client/blob/main/sdk/index.ts#L17

SDK use an edge endpoint but I think this is only used for the beta user so for non-beta user I am getting following error:
```
[PATH_IN_COMPUTER]\node_modules\flagsmith-nodejs\build\sdk\errors.js:30
        return _super !== null && _super.apply(this, arguments) || this;
                                         ^
Error: Invalid request made to Flagsmith API. Response status code: 404
    at new FlagsmithAPIError ([PATH_IN_COMPUTER]\node_modules\flagsmith-nodejs\build\sdk\errors.js:30:42)
    at Flagsmith.<anonymous> ([PATH_IN_COMPUTER]\node_modules\flagsmith-nodejs\build\sdk\index.js:339:35)
    at step ([PATH_IN_COMPUTER]\node_modules\flagsmith-nodejs\build\sdk\index.js:33:23)
    at Object.next ([PATH_IN_COMPUTER]\node_modules\flagsmith-nodejs\build\sdk\index.js:14:53)
    at fulfilled ([PATH_IN_COMPUTER]\node_modules\flagsmith-nodejs\build\sdk\index.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

If I change to `https://api.flagsmith.com/api/v1/` URL, its working.

**Comment by dabeeeenster** [comment]
Edge is released now. If you contact us via in app chat we can upgrade your account to Edge!

**Comment by vongohren** [comment]
This is still live in a freshly installed version of flagsmith from NPM. 

When wil it be released to the wider community?

**Comment by matthewelwell** [comment]
Hi @vongohren, there is no issue here. You need to either migrate your project to our Edge API (see docs [here](https://docs.flagsmith.com/advanced-use/edge-api)) or update the URL to point back to our Core API (https://api.flagsmith.com/api/v1/) as mentioned in the original description of this issue. The default URL will be our Edge API since all new projects are created to use our Edge API. 

Please feel free to reach out via our support if you need assistance moving to our Edge API.
